### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ScreamingHawk** [Shazambom/wallpaperBot#3]
Documentation, particularly for the build process, would be nice. 

Sample config files with placeholder values would make this easier too.

**Comment by Shazambom** [comment]
If you use intellij the java IDE you can easily import the project and compile the java parts. There are also import tools for other IDEs such as Eclipse and Netbeans.

Python is an interpreted language and doesn't need compiling so simply run it but make sure you use pip install to install all of the necessary dependencies. 

To look at the source code look under src/main/java or src/main/python

The config file are simply the client id on the first line and client secret on the second line for the imgur api.
To log into reddit on the first run it will open a popup window and ask you to log in and verify that you are that user. That's about it for config.
